version: "3.8"
services:
  backend:
    build:
      context: ./counter-express
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build:
      context: ./counter-ui
    ports:
      - "8080:8080"

  mysql:
    image: arm64v8/mysql:oracle
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_DATABASE=counter_test
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER = "root"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  db-data:
    driver: local
